name: 01-Building Blocks
on: push

jobs:
  my-first-job:
     runs-on: ubuntu-latest
     steps: 
       - name: Say Hello
         run: echo "Hello, World!"
  my-second-job:
     runs-on: ubuntu-latest
     steps:
       - name: Failed step
         run: |
           echo "I will fail
       - name: Say Goodbye    
         run: echo "Goodbye!"
